### ISSUE TITLE
Using latest libsecp256k1 library occurs "Segmentation fault"

### ISSUE THREAD

**Issue by Yamaguchi** [Yamaguchi/secp256k1-ruby#3]
When i installed latest libsecp256k1 from https://github.com/bitcoin-core/secp256k1/, Calling secp256k1_ecdh method  generated segmentation fault.

OS: Ubunt 18.04 LTS
Ruby 2.5.1

```
/var/lib/gems/2.5.0/gems/secp256k1-ruby-0.4.0/lib/secp256k1/key.rb:116: [BUG] Segmentation fault at 0x0000000000000041
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]

-- Control frame information -----------------------------------------------
c:0045 p:---- s:0241 e:000240 CFUNC  :secp256k1_ecdh
c:0044 p:0097 s:0233 e:000232 METHOD /var/lib/gems/2.5.0/gems/secp256k1-ruby-0.4.0/lib/secp256k1/key.rb:116
c:0043 p:0028 s:0226 e:000225 METHOD /var/lib/gems/2.5.0/gems/noise-ruby-0.6.3/lib/noise/functions/dh/secp256k1.rb:19
c:0042 p:0172 s:0218 e:000216 BLOCK  /var/lib/gems/2.5.0/gems/noise-ruby-0.6.3/lib/noise/state/handshake_state.rb:72 [FINISH]
c:0041 p:---- s:0211 e:000210 CFUNC  :each
c:0040 p:0022 s:0207 e:000206 METHOD /var/lib/gems/2.5.0/gems/noise-ruby-0.6.3/lib/noise/state/handshake_state.rb:60
c:0039 p:0101 s:0199 e:000198 METHOD /var/lib/gems/2.5.0/gems/noise-ruby-0.6.3/lib/noise/connection.rb:63
c:0038 p:0143 s:0192 e:000191 BLOCK  /home/ubuntu/lightningrb/lib/lightning/crypto/transport_handler.rb:161
c:0037 p:0018 s:0183 e:000182 METHOD /var/lib/gems/2.5.0/gems/algebrick-0.7.5/lib/algebrick/matchers/abstract.rb:74
c:0036 p:0038 s:0178 e:000177 METHOD /var/lib/gems/2.5.0/gems/algebrick-0.7.5/lib/algebrick/matching.rb:56
c:0035 p:0026 s:0172 e:000170 BLOCK  /var/lib/gems/2.5.0/gems/algebrick-0.7.5/lib/algebrick/matching.rb:36 [FINISH]
c:0034 p:---- s:0166 e:000165 CFUNC  :each
c:0033 p:0045 s:0162 e:000161 METHOD /var/lib/gems/2.5.0/gems/algebrick-0.7.5/lib/algebrick/matching.rb:35
c:0032 p:0010 s:0156 e:000155 METHOD /var/lib/gems/2.5.0/gems/algebrick-0.7.5/lib/algebrick/matching.rb:23
c:0031 p:0035 s:0148 E:000558 METHOD /home/ubuntu/lightningrb/lib/lightning/crypto/transport_handler.rb:150
c:0030 p:0008 s:0143 e:000142 METHOD /home/ubuntu/lightningrb/lib/lightning/crypto/transport_handler.rb:30
c:0029 p:0014 s:0138 e:000137 METHOD /var/lib/gems/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/context.rb:46
c:0028 p:0009 s:0133 e:000132 METHOD /var/lib/gems/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/behaviour/executes_context.rb:7
c:0027 p:0009 s:0128 e:000127 METHOD /var/lib/gems/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/behaviour/abstract.rb:25
c:0026 p:0021 s:0123 e:000122 METHOD /var/lib/gems/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/behaviour/awaits.rb:15
c:0025 p:0009 s:0118 e:000117 METHOD /var/lib/gems/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/behaviour/abstract.rb:25
c:0024 p:0044 s:0113 e:000112 METHOD /var/lib/gems/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/behaviour/linking.rb:60
c:0023 p:0009 s:0108 e:000107 METHOD /var/lib/gems/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/behaviour/abstract.rb:25
c:0022 p:0067 s:0103 e:000102 METHOD /var/lib/gems/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/behaviour/termination.rb:55
c:0021 p:0009 s:0096 e:000095 METHOD /var/lib/gems/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/behaviour/abstract.rb:25
c:0020 p:0031 s:0091 e:000090 METHOD /var/lib/gems/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/behaviour/removes_child.rb:10
c:0019 p:0009 s:0086 e:000085 METHOD /var/lib/gems/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/behaviour/abstract.rb:25
c:0018 p:0006 s:0081 e:000080 METHOD /var/lib/gems/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/behaviour/sets_results.rb:14
c:0017 p:0008 s:0074 e:000073 METHOD /var/lib/gems/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/core.rb:162
c:0016 p:0020 s:0069 E:000380 BLOCK  /var/lib/gems/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/core.rb:96
c:0015 p:0023 s:0066 e:000065 BLOCK  /var/lib/gems/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/core.rb:119
c:0014 p:0003 s:0062 e:000061 BLOCK  /var/lib/gems/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/synchronization/mutex_lockable_object.rb:41 [FINISH]
c:0013 p:---- s:0059 e:000058 CFUNC  :synchronize
c:0012 p:0018 s:0055 e:000054 METHOD /var/lib/gems/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/synchronization/mutex_lockable_object.rb:41
c:0011 p:0006 s:0051 e:000050 BLOCK  /var/lib/gems/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/core.rb:116 [FINISH]
c:0010 p:0013 s:0048 e:000047 METHOD /var/lib/gems/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/serialized_execution.rb:18
c:0009 p:0005 s:0044 e:000043 METHOD /var/lib/gems/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/serialized_execution.rb:96
c:0008 p:0007 s:0039 e:000038 BLOCK  /var/lib/gems/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/serialized_execution.rb:77 [FINISH]
c:0007 p:0009 s:0036 e:000035 METHOD /var/lib/gems/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:348
c:0006 p:0049 s:0028 e:000027 BLOCK  /var/lib/gems/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:337 [FINISH]
c:0005 p:---- s:0022 e:000021 CFUNC  :loop
c:0004 p:0006 s:0018 e:000017 BLOCK  /var/lib/gems/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:320 [FINISH]
c:0003 p:---- s:0015 e:000014 CFUNC  :catch
c:0002 p:0020 s:0010 e:000009 BLOCK  /var/lib/gems/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:319 [FINISH]
c:0001 p:---- s:0003 e:000002 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/var/lib/gems/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
/var/lib/gems/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/var/lib/gems/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/var/lib/gems/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/var/lib/gems/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/var/lib/gems/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/var/lib/gems/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/serialized_execution.rb:77:in `block in call_job'
/var/lib/gems/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/serialized_execution.rb:96:in `work'
/var/lib/gems/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/serialized_execution.rb:18:in `call'
/var/lib/gems/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/core.rb:116:in `block in schedule_execution'
/var/lib/gems/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/synchronization/mutex_lockable_object.rb:41:in `synchronize'
/var/lib/gems/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/synchronization/mutex_lockable_object.rb:41:in `synchronize'
/var/lib/gems/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/synchronization/mutex_lockable_object.rb:41:in `block in synchronize'
/var/lib/gems/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/core.rb:119:in `block (2 levels) in schedule_execution'
/var/lib/gems/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/core.rb:96:in `block in on_envelope'
/var/lib/gems/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/core.rb:162:in `process_envelope'
/var/lib/gems/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/behaviour/sets_results.rb:14:in `on_envelope'
/var/lib/gems/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/behaviour/abstract.rb:25:in `pass'
/var/lib/gems/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/behaviour/removes_child.rb:10:in `on_envelope'
/var/lib/gems/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/behaviour/abstract.rb:25:in `pass'
/var/lib/gems/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/behaviour/termination.rb:55:in `on_envelope'
/var/lib/gems/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/behaviour/abstract.rb:25:in `pass'
/var/lib/gems/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/behaviour/linking.rb:60:in `on_envelope'
/var/lib/gems/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/behaviour/abstract.rb:25:in `pass'
/var/lib/gems/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/behaviour/awaits.rb:15:in `on_envelope'
/var/lib/gems/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/behaviour/abstract.rb:25:in `pass'
/var/lib/gems/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/behaviour/executes_context.rb:7:in `on_envelope'
/var/lib/gems/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/context.rb:46:in `on_envelope'
/home/ubuntu/lightningrb/lib/lightning/crypto/transport_handler.rb:30:in `on_message'
/home/ubuntu/lightningrb/lib/lightning/crypto/transport_handler.rb:150:in `next'
/var/lib/gems/2.5.0/gems/algebrick-0.7.5/lib/algebrick/matching.rb:23:in `match'
/var/lib/gems/2.5.0/gems/algebrick-0.7.5/lib/algebrick/matching.rb:35:in `match?'
/var/lib/gems/2.5.0/gems/algebrick-0.7.5/lib/algebrick/matching.rb:35:in `each'
/var/lib/gems/2.5.0/gems/algebrick-0.7.5/lib/algebrick/matching.rb:36:in `block in match?'
/var/lib/gems/2.5.0/gems/algebrick-0.7.5/lib/algebrick/matching.rb:56:in `match_value'
/var/lib/gems/2.5.0/gems/algebrick-0.7.5/lib/algebrick/matchers/abstract.rb:74:in `assigns'
/home/ubuntu/lightningrb/lib/lightning/crypto/transport_handler.rb:161:in `block in next'
/var/lib/gems/2.5.0/gems/noise-ruby-0.6.3/lib/noise/connection.rb:63:in `write_message'
/var/lib/gems/2.5.0/gems/noise-ruby-0.6.3/lib/noise/state/handshake_state.rb:60:in `write_message'
/var/lib/gems/2.5.0/gems/noise-ruby-0.6.3/lib/noise/state/handshake_state.rb:60:in `each'
/var/lib/gems/2.5.0/gems/noise-ruby-0.6.3/lib/noise/state/handshake_state.rb:72:in `block in write_message'
/var/lib/gems/2.5.0/gems/noise-ruby-0.6.3/lib/noise/functions/dh/secp256k1.rb:19:in `dh'
/var/lib/gems/2.5.0/gems/secp256k1-ruby-0.4.0/lib/secp256k1/key.rb:116:in `ecdh'
/var/lib/gems/2.5.0/gems/secp256k1-ruby-0.4.0/lib/secp256k1/key.rb:116:in `secp256k1_ecdh'

-- Machine register context ------------------------------------------------
 RIP: 0x0000000000000041 RBP: 0x0005cb110fc1c363 RSP: 0x00007f3f0f3987c8
 RAX: 0x0000000000000041 RBX: 0x00007f3f0f398998 RCX: 0x000055e446715800
 RDX: 0x00007f3f0f3993e0 RDI: 0x00007f3f00376880 RSI: 0x00007f3f0f3993c0
  R8: 0x00007f3f0f3993c0  R9: 0x00007f3f0f3993e0 R10: 0x0009a089259c2cf4
 R11: 0x00004a507d061520 R12: 0x00096db7fceed431 R13: 0x0007d26687edee25
 R14: 0x00007f3f0f398970 R15: 0x00007f3f0f398910 EFL: 0x0000000000010203

-- C level backtrace information -------------------------------------------
```

**Comment by Yamaguchi** [comment]
Fixed at eb24b9f2079c2b8536f7a11d3646d974a17067ab
